dependencies:
- name: elasticsearch
  version: "7.7.1"
  repository: https://helm.elastic.co
- name: kibana
  version: "7.7.1"
  repository: https://helm.elastic.co
- name: fluent-bit
  version: "2.8.16"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: fluent-bit.enabled
- name: elasticsearch-curator
  version: "2.1.5"
  repository: https://kubernetes-charts.storage.googleapis.com/